name: dev-table
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - pip:
      - pandas
      - ipykernel
      - matplotlib
      - natsort
      - numpy
      - pyarrow
      - pyqt5
      - pyqtgraph
      - scikit-image
      - scipy
      - seaborn
      - sympy
      - tifffile
