import os
import numpy as np
import matplotlib.pyplot as plt
from json import load
from pathlib import Path
from scipy.constants import speed_of_light as c


def ffta(x=None, N=None, Dim=None):
    
    if N is None:
        N = np.max(x.shape)
    if Dim is None:
        Dim = np.argmax(x.shape)
    
    y = np.fft.fftshift(np.fft.fft(x, n=N, axis=Dim))
    
    if N % 2 == 0:
        # even
        f = np.arange(-N/2, N/2) / N
    else:
        # odd
        f = np.arange(-(N-1)/2, (N-1)/2 + 1) / N
        
    return y, f

def read_optical_axis_file(file_path, size):
     """
     Reads the binary file generated by compute_approx_optical_axis.
     Args:
     file_path (str): Path to the binary file.
     size (int): Number of elements in each array.
     Returns:
     tuple: A tuple containing:
     - freq_optical_pos_Hz (numpy.ndarray): Positive optical frequencies.
     - freq_optical_neg_Hz (numpy.ndarray): Negative optical frequencies.
     - spcTemplate (numpy.ndarray): Spectrum template.
     """
     try:
         # Read the binary file
         with open(file_path, 'rb') as file:
             # Read data from file
             freq_optical_pos_Hz = np.frombuffer(file.read(size * 8), dtype=np.float64)
             freq_optical_neg_Hz = np.frombuffer(file.read(size * 8), dtype=np.float64)
             spcTemplate = np.frombuffer(file.read(size * 8), dtype=np.float64)
             return freq_optical_pos_Hz, freq_optical_neg_Hz, spcTemplate
     except IOError:
         raise IOError(f"Failed to open file for reading: {file_path}")


# Path to your folder with .bin files
folder = Path(r"C:\Users\Splinter-User\Documents\Data\PUG_data\harm2_self-cor_10min\20251002_10h34m43s")


# Read parameter files
with open(folder/'apriori_params.json', 'r') as file:
    apriori = load(file)
with open(folder/'computed_params.json', 'r') as file:
    computed = load(file)
with open(folder/'gageCard_params.json', 'r') as file:
    gage = load(file)

bin_folder = folder / 'Output_data/Channel1'
# Collect .bin files (sorted for consistency)
data_files = sorted([f for f in os.listdir(bin_folder) if f.endswith(".bin")])
data_list = []
for fname in data_files:
    filepath = os.path.join(bin_folder, fname)
    
    # Load raw binary floats (32-bit)
    numbers = np.fromfile(filepath, dtype=np.float32)
    
    # Convert to complex: (real, imag) pairs
    complex_data = numbers[0::2] + 1j * numbers[1::2]
    data_list.append(complex_data)

# Handle different lengths by padding with NaN
max_len = max(len(d) for d in data_list)
matrix = np.full((max_len, len(data_list)), np.nan, dtype=complex)

for i, d in enumerate(data_list):
    matrix[:len(d), i] = d

# Compute average across files (ignoring NaNs for uneven lengths)
avg_signal = np.nanmean(matrix, axis=1)
# Path to your folder with .bin files
# folder = r"C:\Users\Splinter-User\Documents\Data\PUG_data\harm2_self-cor_10min\20251002_10h34m43s"

# # Collect .bin files (sorted for consistency)
# files = sorted([f for f in os.listdir(folder) if f.endswith(".bin")])
# files = files[1]
# filepath = os.path.join(folder, files)
# freq_pos, freq_neg, spectrum = read_optical_axis_file(filepath, len(avg_signal))
# Plot all signals (real part as example)
# plt.figure(figsize=(10, 6))
# for i in range(140,matrix.shape[1]):
#     plt.plot(matrix[:, i].real, label=f'File {i+1}', alpha=0.7)
# plt.plot(avg_signal.real, 'k--', linewidth=2, label='Average')

# plt.title("Complex Data Files (Real part)")
# plt.xlabel("Index")
# plt.ylabel("Amplitude")
# plt.legend()
# plt.show()

fs_hz = gage['sampling_rate_Hz']
dfr_hz = computed['dfr']
fr_hz = apriori['fr_approx_Hz']
fcw_hz = 1e9 * c / apriori['reference1_laser_wvl_nm']

[spc,f] = ffta(avg_signal)
electrical_axis_hz = fs_hz * f
optical_axis_hz = electrical_axis_hz * fr_hz / dfr_hz + 2 * fcw_hz
time_axis_s = np.linspace(start=0, stop=len(f) / fs_hz, num=len(f))

# Optical frequency spectrum
plt.figure()
plt.plot(optical_axis_hz * 1e-12, np.abs(spc))
# plt.plot(freq_pos/1e12,np.abs(spc))
plt.xlabel('Approx. Optical Frequency (THz)')
plt.ylabel('Intensity (arb.)')
plt.grid()
plt.tight_layout()

# Electrical frequency spectrum
plt.figure()
plt.plot(electrical_axis_hz * 1e-6, np.abs(spc))
plt.xlabel('Electrical Frequency (MHz)')
plt.ylabel('Intensity (arb.)')
plt.grid()
plt.tight_layout()

# Interferogram (real)
center_us = 1e6 * (time_axis_s[-1] - time_axis_s[0])/2
window_us = 20
plt.figure()
plt.plot(time_axis_s * 1e6, np.real(avg_signal),label='Real part',alpha=.7)
plt.plot(time_axis_s * 1e6, np.imag(avg_signal), label='Imag part',alpha=.7)
plt.xlabel(r'Time ($\mu$s)')
plt.ylabel('Intensity (arb.)')
plt.xlim(center_us - window_us/2, center_us + window_us/2)
plt.grid()
plt.legend()
plt.tight_layout()
plt.show()
