# -*- coding: utf-8 -*-
"""
Created on Wed Oct  1 15:10:18 2025

@author: Diddams
"""

import os
import numpy as np
import matplotlib.pyplot as plt
import numpy as np
from numpy.fft import fft, fftshift, rfft, irfft, ifftshift, fftfreq

def ffta(x=None, N=None, Dim=None):
    
    if N is None:
        N = np.max(x.shape)
    if Dim is None:
        Dim = np.argmax(x.shape)
    
    y = np.fft.fftshift(np.fft.fft(x, n=N, axis=Dim))
    
    if N % 2 == 0:
        # even
        f = np.arange(-N/2, N/2) / N
    else:
        # odd
        f = np.arange(-(N-1)/2, (N-1)/2 + 1) / N
        
    return y, f

def read_optical_axis_file(file_path, size):
     """
     Reads the binary file generated by compute_approx_optical_axis.
     Args:
     file_path (str): Path to the binary file.
     size (int): Number of elements in each array.
     Returns:
     tuple: A tuple containing:
     - freq_optical_pos_Hz (numpy.ndarray): Positive optical frequencies.
     - freq_optical_neg_Hz (numpy.ndarray): Negative optical frequencies.
     - spcTemplate (numpy.ndarray): Spectrum template.
     """
     try:
         # Read the binary file
         with open(file_path, 'rb') as file:
             # Read data from file
             freq_optical_pos_Hz = np.frombuffer(file.read(size * 8), dtype=np.float64)
             freq_optical_neg_Hz = np.frombuffer(file.read(size * 8), dtype=np.float64)
             spcTemplate = np.frombuffer(file.read(size * 8), dtype=np.float64)
             return freq_optical_pos_Hz, freq_optical_neg_Hz, spcTemplate
     except IOError:
         raise IOError(f"Failed to open file for reading: {file_path}")


# Path to your folder with .bin files
folder = r"/home/mike/Documents/Boulder_PhD/Data/20251023_10h18m12s/Output_data/Channel1"

# Collect .bin files (sorted for consistency)
files = sorted([f for f in os.listdir(folder) if f.endswith(".bin")])

data_list = []
for fname in files:
    filepath = os.path.join(folder, fname)
    
    # Load raw binary floats (32-bit)
    numbers = np.fromfile(filepath, dtype=np.float32)
    
    # Convert to complex: (real, imag) pairs
    complex_data = numbers[0::2] + 1j * numbers[1::2]
    data_list.append(complex_data)

# Handle different lengths by padding with NaN
max_len = max(len(d) for d in data_list)
matrix = np.full((max_len, len(data_list)), np.nan, dtype=complex)

for i, d in enumerate(data_list):
    matrix[:len(d), i] = d

# Compute average across files (ignoring NaNs for uneven lengths)
avg_signal = np.nanmean(matrix, axis=1)
# Path to your folder with .bin files
#%% Diagnostics from Mathieu

folder = r"/home/mike/Documents/Boulder_PhD/Data/20251023_10h18m12s"

# Collect .bin files (sorted for consistency)
files = sorted([f for f in os.listdir(folder) if f.endswith(".bin")])
files = files[1]
filepath = os.path.join(folder, files)
freq_pos, freq_neg, spectrum = read_optical_axis_file(filepath, len(avg_signal))

#%% Double checking how things look before analysis
c = 299792458
ppigm = np.size(avg_signal)
dfr_gpu = 32.574
fs=100e6
fr1 = 100e6 + 31.840
fr2 = 100e6 + 31.840 + dfr_gpu
f01 = -35e6
f02 = -36e6
fb1 = 36e6
fb2 = -27e6
df0 = f01-f02
dfb = fb1-fb2
nu_cw = 193.405065e12

spc = fftshift(fft(avg_signal))
f = fftshift(fftfreq(len(avg_signal)))
avg_spec = np.abs(spc)


#%% Defining a new optical axis

k = np.arange(ppigm)

nu_cw_PUG = 193405160580183.84
num_harmonic = 2

mode_num_1 = 1934050
mode_num_2 = 1934050

# phi_c = num_harmonic*((2*np.pi*k)/fs)*(mode_num_1*dfr_gpu + df0) + (2*np.pi*k*fr1)/(2*fs)

# avg_signal_unwrapped = avg_signal*np.exp(-phi_c*1j)
# [avg_spc_unwrapped,f] = ffta(avg_signal_unwrapped)

# plt.figure('Unwrapped Electrical Comb')
# plt.plot(fs*f,np.abs(avg_spec))
# plt.xlabel('RF Frequency (Hz)')
# plt.ylabel('Signal (a.u)')

# # opt_axis = rf_to_opt*(f*fs - num_harmonic*dfb- (num_harmonic-1)*df0) + num_harmonic*nu_cw_PUG - num_harmonic*fb1 - (num_harmonic - 1)*f01
# #opt_axis = rf_to_opt*(f*fs) + (num_harmonic*nu_cw_PUG) - (num_harmonic*fb1) - ((num_harmonic-1)*f01)

f_shift = num_harmonic*(mode_num_1 * fr1 + f01)
f_N = f*ppigm
opt_axis = np.sign(dfr_gpu)*f_N*fr1+f_shift


# plt.figure('Unwrapped optical comb')
# plt.plot(opt_axis/1e12,np.abs(avg_spec))
# plt.xlabel('Optical Frequency (THz)')
# plt.ylabel('DCS signal')
# #plt.xlim(384.2,384.27)
# #plt.ylim(70000,120000)

# nu_Rb87_D2 = 384.2304844685e12
# nu_split_Rb87_D2_f1 = -2.56300597908911e9
# nu_split_Rb87_D2_f2 = 4.27167663181519e9
# Rb87_D2_nu1 = (nu_Rb87_D2 + nu_split_Rb87_D2_f1)/1e12
# Rb87_D2_nu2 = (nu_Rb87_D2 + nu_split_Rb87_D2_f2)/1e12

# nu_Rb87_D1 = 377.1074635e12
# nu_split_Rb87_D1_f1 = -2.56300597908911e9
# nu_split_Rb87_D1_f2 = 4.27167663181519e9
# Rb87_D1_nu1 = (nu_Rb87_D1 + nu_split_Rb87_D1_f1)/1e12
# Rb87_D1_nu2 = (nu_Rb87_D1 + nu_split_Rb87_D1_f2)/1e12

# nu_Rb85_D2 = 384.230406373e12
# nu_split_Rb85_D2_f2 = -1.2648885163e9
# nu_split_Rb85_D2_f3 = 1.7708439228e9
# Rb85_D2_nu1 = (nu_Rb85_D2 + nu_split_Rb85_D2_f2)/1e12
# Rb85_D2_nu2 = (nu_Rb85_D2 + nu_split_Rb85_D2_f3)/1e12

# nu_Rb85_D1 = 377.107385690e12
# nu_split_Rb85_D1_f2 = -1.2648885163e9
# nu_split_Rb85_D1_f3 = 1.7708439228e9
# Rb85_D1_nu1 = (nu_Rb85_D1 + nu_split_Rb85_D1_f2)/1e12
# Rb85_D1_nu2 = (nu_Rb85_D1 + nu_split_Rb85_D1_f3)/1e12


# plt.vlines(Rb87_D2_nu1,0,np.max(np.abs(avg_spec)),color='black')
# plt.vlines(Rb87_D2_nu2,0,np.max(np.abs(avg_spec)),color='black')
# plt.vlines(Rb87_D1_nu1,0,np.max(np.abs(avg_spec)),color='black')
# plt.vlines(Rb87_D1_nu2,0,np.max(np.abs(avg_spec)),color='black')
# plt.vlines(Rb85_D2_nu1,0,np.max(np.abs(avg_spec)),color='black')
# plt.vlines(Rb85_D2_nu2,0,np.max(np.abs(avg_spec)),color='black')
# plt.vlines(Rb85_D1_nu1,0,np.max(np.abs(avg_spec)),color='black')
# plt.vlines(Rb85_D1_nu2,0,np.max(np.abs(avg_spec)),color='black')


# #np.savetxt(r'C:\Users\Diddams\Desktop\for emily\DCSiodine.txt',np.array(np.abs(avg_spec)))
# #np.savetxt(r'C:\Users\Diddams\Desktop\for emily\DCSiodine_x.txt',np.array(opt_axis))
# plt.show()

#%% Cepstral

i_spec = avg_spec

absorbance = -np.log(i_spec)

# plt.plot(absorbance)

# plt.show()
# a1 = 1388000
a1 = 388000
a2 = 1692000
low_cut = opt_axis[a1]
high_cut = opt_axis[a2]
print(low_cut, high_cut)
mask = (opt_axis >=low_cut) & (opt_axis <= high_cut)
# absorbance_cut = absorbance[a1:a2]
absorbance_cut = absorbance[mask]
# plt.plot(absorbance_cut)
# plt.plot(i_spec[mask])

# full_spectrum = np.concatenate((absorbance_cut,absorbance_cut[-2:0:-1].conj()))
# ift = np.fft.ifft(full_spectrum)
ift = irfft(absorbance_cut)
baseline = np.copy(ift)
# plt.plot(ift)

# cepstral_cuton = 2000
cepstral_cuton = 5000
cepstral_cutoff = 506100

ift[0:cepstral_cuton] = 0
ift[cepstral_cutoff:] = 0
# baseline[cepstral_cuton:-cepstral_cuton] = 0

#etalon removal
#ift[7145:7257] = 0
#ift[2067:2089] = 0
#ift[2380308:2380343] = 0
#ift[2375128:2375267] = 0

# plt.plot(ift)

# plt.show()
ft = rfft(ift)
ft2 = rfft(baseline)
baseline_removed = np.abs(np.exp(-ft))
# measured_baseline = np.abs(np.exp(-ft2))

#plt.plot(baseline_removed_i2)


# opt_freq_cut = opt_axis[a1:a2]
opt_freq_cut = opt_axis[mask]
# plt.figure()
# plt.plot(opt_freq_cut/1e12,np.exp(-absorbance_cut))
# plt.plot(opt_freq_cut/1e12,measured_baseline)
# plt.show()

# plt.figure('Baseline-Corrected Transmission')
# plt.plot((opt_freq_cut/1e12),baseline_removed,label='')
# plt.xlabel('Optical Frequency (THz)')
# plt.ylabel('Baseline-Corrected Transmission')

# plt.show()

plt.figure('D2')
plt.plot((opt_freq_cut/1e12),baseline_removed,label='')
plt.xlabel('Optical Frequency (THz)')
plt.ylabel('Baseline-Corrected Transmission')
plt.xlim(384.2,384.26)
plt.ylim(.05,1.2)
plt.legend()

plt.show()
plt.figure('D1')
plt.plot((opt_freq_cut/1e12),baseline_removed,label='')
plt.xlabel('Optical Frequency (THz)')
plt.ylabel('Baseline-Corrected Transmission')
plt.xlim(377.06,377.16)
plt.ylim(.4,1.25)
plt.legend()

plt.show()